export { default as Menu } from './Menu'
export { default as Footer } from './Footer'
export { default as Newsletter } from './Newsletter'
export { default as Location } from './Location'
export { Model } from './Model'
export { Slide } from './Slide'
export { default as CardFilme } from './CardFilme'
